stages:
  - build

variables:
  CI_DOCKER_REGISTRY: "ciregistry.espressif.cn:8443"
  ESP_ZIGBEE_SDK_PATH: "$CI_PROJECT_DIR/esp-zigbee-sdk"
  ESP_ZBOSS_LIB_PATH: "$CI_PROJECT_DIR"

before_script:
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -n "${GITLAB_KEY}" >~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 >~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >>~/.ssh/config

.setup_idf: &setup_idf
  - cd $CI_PROJECT_DIR/..
  - rm -rf esp-idf
  - git clone --recursive -b master ${ESP_IDF_URL}
  - cd esp-idf
  - git checkout --track origin/$CI_COMMIT_REF_NAME || git branch
  - git submodule sync --recursive
  - git submodule update --recursive --init
  - ./install.sh
  - . ./export.sh

.setup_esp_sdk: &setup_esp_sdk
  - cd $CI_PROJECT_DIR
  - git clone --recursive -b main ${ESP_ZIGBEE_SDK_URL}
  - cd esp-zigbee-sdk
  - git checkout --track origin/$CI_COMMIT_REF_NAME || git branch
  - git submodule update --recursive --init

.build_esp_idf_zigbee_gateway_template: 
  stage: build
  image: ${CI_DOCKER_REGISTRY}/esp-env-v5.0:2
  variables:
    TARGET_NAME: "esp32"
    EXAMPLE_PATH: ""
  allow_failure: false
  script:
    - *setup_idf
    - *setup_esp_sdk
    - cd $CI_PROJECT_DIR/..
    - cp -r ${ESP_ZBOSS_LIB_PATH} ${IDF_PATH}/components/espressif__esp-zboss-lib
    - cp -r ${ESP_ZIGBEE_SDK_PATH}/components/esp-zigbee-lib ${IDF_PATH}/components/esp-zigbee-lib
    - cd ${IDF_PATH}/"${EXAMPLE_PATH}"
    - sed -i '/esp-zboss-lib/d' main/idf_component.yml
    - sed -i '/esp-zigbee-lib/d' main/idf_component.yml
    - idf.py fullclean 
    - idf.py set-target "${TARGET_NAME}"
    - idf.py build

.build_esp_idf_light_example_template:
  stage: build
  image: ${CI_DOCKER_REGISTRY}/esp-env-v5.0:2
  variables:
    TARGET_NAME: ""
    EXAMPLE_PATH: ""
  allow_failure: false
  script:
    - *setup_idf
    - *setup_esp_sdk
    - cd ${ESP_ZBOSS_LIB_PATH}
    - cp -r ${ESP_ZBOSS_LIB_PATH} ${IDF_PATH}/components/espressif__esp-zboss-lib
    - cp -r ${ESP_ZIGBEE_SDK_PATH}/components/esp-zigbee-lib ${IDF_PATH}/components/esp-zigbee-lib
    - cd ${IDF_PATH}/"${EXAMPLE_PATH}"
    - sed -i '/esp-zboss-lib/d' main/idf_component.yml
    - sed -i '/esp-zigbee-lib/d' main/idf_component.yml
    - idf.py fullclean
    - idf.py --preview set-target "${TARGET_NAME}"
    - idf.py build

.build_esp_idf_non_light_example_template:
  stage: build
  image: ${CI_DOCKER_REGISTRY}/esp-env-v5.0:2
  variables:
    TARGET_NAME: ""
    EXAMPLE_PATH: ""
  allow_failure: false
  script:
    - *setup_idf
    - *setup_esp_sdk
    - cp -r ${ESP_ZBOSS_LIB_PATH} ${IDF_PATH}/components/espressif__esp-zboss-lib
    - cp -r ${ESP_ZIGBEE_SDK_PATH}/components/esp-zigbee-lib ${IDF_PATH}/components/esp-zigbee-lib
    - cd ${IDF_PATH}/"${EXAMPLE_PATH}"
    - sed -i '/esp-zboss-lib/d' main/idf_component.yml
    - sed -i '/esp-zigbee-lib/d' main/idf_component.yml
    - idf.py fullclean
    - idf.py --preview set-target "${TARGET_NAME}"
    - idf.py build

.build_esp_sdk_zigbee_gateway_template:
    stage: build
    image: ${CI_DOCKER_REGISTRY}/esp-env-v5.0:2
    variables:
        TARGET_NAME: ""
        EXAMPLE_PATH: ""
    allow_failure: false
    script:
        - *setup_idf
        - *setup_esp_sdk
        - cp -r ${ESP_ZBOSS_LIB_PATH} ${IDF_PATH}/components/espressif__esp-zboss-lib
        - cd ${ESP_ZIGBEE_SDK_PATH}/examples/esp_zigbee_rcp
        - sed -i '/esp-zboss-lib/d' main/idf_component.yml
        - idf.py --preview set-target esp32h4
        - idf.py build
        - cd ${ESP_ZIGBEE_SDK_PATH}/"${EXAMPLE_PATH}"
        - sed -i '/esp-zboss-lib/d' main/idf_component.yml
        - idf.py fullclean
        - idf.py set-target "${TARGET_NAME}"
        - idf.py build


.build_esp_zigbee_sdk_example_zigbee_template:
    stage: build
    image: ${CI_DOCKER_REGISTRY}/esp-env-v5.0:2
    variables:
        TARGET_NAME: ""
        EXAMPLE_PATH: ""
    allow_failure: false
    script:
        - *setup_idf
        - *setup_esp_sdk
        - cp -r ${ESP_ZBOSS_LIB_PATH} ${IDF_PATH}/components/espressif__esp-zboss-lib
        - cd ${ESP_ZIGBEE_SDK_PATH}/"${EXAMPLE_PATH}"
        - sed -i '/esp-zboss-lib/d' main/idf_component.yml
        - idf.py fullclean
        - idf.py --preview set-target "${TARGET_NAME}"
        - idf.py build

.build_esp_zigbee_sdk_example_non_h4_zigbee_template:
    stage: build
    image: ${CI_DOCKER_REGISTRY}/esp-env-v5.0:2
    variables:
        TARGET_NAME: ""
        EXAMPLE_PATH: ""
    allow_failure: false
    script:
        - *setup_idf
        - *setup_esp_sdk
        - cp -r ${ESP_ZBOSS_LIB_PATH} ${IDF_PATH}/components/espressif__esp-zboss-lib
        - cd ${ESP_ZIGBEE_SDK_PATH}/"${EXAMPLE_PATH}"
        - sed -i '/esp-zboss-lib/d' main/idf_component.yml
        - idf.py fullclean
        - idf.py set-target "${TARGET_NAME}"
        - idf.py build

# build esp_zigbee_gateway for esp32/esp32c3/esp32s2/esp32s3
build_idf_esp32_zigbee_gateway_examples:
  extends: .build_esp_idf_zigbee_gateway_template
  variables:
    TARGET_NAME: "esp32"
    EXAMPLE_PATH: "examples/zigbee/esp_zigbee_gateway"

build_idf_esp32c3_zigbee_gateway_examples:
  extends: .build_esp_idf_zigbee_gateway_template
  variables:
    TARGET_NAME: "esp32c3"
    EXAMPLE_PATH: "examples/zigbee/esp_zigbee_gateway"

build_idf_esp32s2_zigbee_gateway_examples:
  extends: .build_esp_idf_zigbee_gateway_template
  variables:
    TARGET_NAME: "esp32s2"
    EXAMPLE_PATH: "examples/zigbee/esp_zigbee_gateway"

build_idf_esp32s3_zigbee_gateway_examples:
  extends: .build_esp_idf_zigbee_gateway_template
  variables:
    TARGET_NAME: "esp32s3"
    EXAMPLE_PATH: "examples/zigbee/esp_zigbee_gateway"

# build esp_zigbee_rcp for esp32h4beta2
build_idf_esp32h4_zigbee_rcp_examples:
  extends: .build_esp_idf_non_light_example_template
  variables:
    TARGET_NAME: "esp32h4"
    EXAMPLE_PATH: "examples/zigbee/esp_zigbee_rcp"

# build HA on off light for esp32h4beta2
build_idf_esp32h4_on_off_light_examples:
  extends: .build_esp_idf_light_example_template
  variables:
    TARGET_NAME: "esp32h4"
    EXAMPLE_PATH: "examples/zigbee/light_sample/HA_on_off_light"

# build HA on off switch for esp32h4beta2
build_idf_esp32h4_on_off_switch_examples:
  extends: .build_esp_idf_non_light_example_template
  variables:
    TARGET_NAME: "esp32h4"
    EXAMPLE_PATH: "examples/zigbee/light_sample/HA_on_off_switch"

# build esp_zigbee_gateway for esp32
build_sdk_esp32_zigbee_gateway_examples:
  extends: .build_esp_sdk_zigbee_gateway_template
  variables:
    TARGET_NAME: "esp32"
    EXAMPLE_PATH: "examples/esp_zigbee_gateway"

# build esp_zigbee_gateway for esp32s3
build_sdk_esp32s3_zigbee_gateway_examples:
  extends: .build_esp_sdk_zigbee_gateway_template
  variables:
    TARGET_NAME: "esp32s3"
    EXAMPLE_PATH: "examples/esp_zigbee_gateway"

# build esp_zigbee_gateway for esp32c3
build_sdk_esp32c3_zigbee_gateway_examples:
  extends: .build_esp_sdk_zigbee_gateway_template
  variables:
    TARGET_NAME: "esp32c3"
    EXAMPLE_PATH: "examples/esp_zigbee_gateway"

# build esp_zigbee_gateway for esp32s2
build_sdk_esp32s2_zigbee_gateway_examples:
  extends: .build_esp_sdk_zigbee_gateway_template
  variables:
    TARGET_NAME: "esp32s2"
    EXAMPLE_PATH: "examples/esp_zigbee_gateway"

#build esp_zigbee customized_client for esp32h4beta2
build_sdk_esp32h4_beta2_zigbee_customized_client_examples:
  extends: .build_esp_zigbee_sdk_example_zigbee_template
  variables:
    TARGET_NAME: "esp32h4"
    EXAMPLE_PATH: "examples/esp_zigbee_customized_devices/customized_client"

#build esp_zigbee customized_server for esp32h4beta2
build_sdk_esp32h4_beta2_zigbee_customized_server_examples:
  extends: .build_esp_zigbee_sdk_example_zigbee_template
  variables:
    TARGET_NAME: "esp32h4"
    EXAMPLE_PATH: "examples/esp_zigbee_customized_devices/customized_server"

#build esp_zigbee HA color dimmable light for esp32h4beta2
build_sdk_esp32h4_beta2_zigbee_color_dimmable_light_examples:
  extends: .build_esp_zigbee_sdk_example_zigbee_template
  variables:
    TARGET_NAME: "esp32h4"
    EXAMPLE_PATH: "examples/esp_zigbee_HA_sample/HA_color_dimmable_light"

#build esp_zigbee HA color dimmable switch for esp32h4beta2
build_sdk_esp32h4_beta2_zigbee_color_dimmable_switch_examples:
  extends: .build_esp_zigbee_sdk_example_zigbee_template
  variables:
    TARGET_NAME: "esp32h4"
    EXAMPLE_PATH: "examples/esp_zigbee_HA_sample/HA_color_dimmable_switch"

#build esp_zigbee HA on_off light for esp32h4beta2
build_sdk_esp32h4_beta2_zigbee_on_off_light_examples:
  extends: .build_esp_zigbee_sdk_example_zigbee_template
  variables:
    TARGET_NAME: "esp32h4"
    EXAMPLE_PATH: "examples/esp_zigbee_HA_sample/HA_on_off_light"

#build esp_zigbee HA color dimmable light for esp32h4beta2
build_sdk_esp32h4_beta2_zigbee_on_off_switch_examples:
  extends: .build_esp_zigbee_sdk_example_zigbee_template
  variables:
    TARGET_NAME: "esp32h4"
    EXAMPLE_PATH: "examples/esp_zigbee_HA_sample/HA_on_off_switch"

#build esp_zigbee cli for esp32h4beta2
build_sdk_esp32h4_beta2_zigbee_cli_examples:
  extends: .build_esp_zigbee_sdk_example_zigbee_template
  variables:
    TARGET_NAME: "esp32h4"
    EXAMPLE_PATH: "examples/esp_zigbee_cli"

#build esp_zigbee cli for esp32
build_sdk_esp32_zigbee_cli_examples:
  extends: .build_esp_zigbee_sdk_example_non_h4_zigbee_template
  variables:
    TARGET_NAME: "esp32"
    EXAMPLE_PATH: "examples/esp_zigbee_cli"

#build esp_zigbee cli for esp32c3
build_sdk_esp32c3_zigbee_cli_examples:
  extends: .build_esp_zigbee_sdk_example_non_h4_zigbee_template
  variables:
    TARGET_NAME: "esp32c3"
    EXAMPLE_PATH: "examples/esp_zigbee_cli"

#build esp_zigbee cli for esp32s2
build_sdk_esp32s2_zigbee_cli_examples:
  extends: .build_esp_zigbee_sdk_example_non_h4_zigbee_template
  variables:
    TARGET_NAME: "esp32s2"
    EXAMPLE_PATH: "examples/esp_zigbee_cli"

#build esp_zigbee cli for esp32s3
build_sdk_esp32s3_zigbee_cli_examples:
  extends: .build_esp_zigbee_sdk_example_non_h4_zigbee_template
  variables:
    TARGET_NAME: "esp32s3"
    EXAMPLE_PATH: "examples/esp_zigbee_cli"
